server:
  port: 9080
  address: localhost
  

spring:
  banner:
    location: classpath:/cmdb.txt
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_schema?characterEncoding=utf8&serverTimezone=UTC
    username: root123
    ***REMOVED***
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

cmdb:
  datasource:
    schema: db_schema


    #Authentication provider options: LOCAL or CAS. Effective ONLY when security-enabled set as true.
    authentication-provider: LOCAL

    #Effective ONLY when security-enabled set as true and authentication-provider turns to CAS
    
    #Effective ONLY when security-enabled set as true
    whitelist-ip-address:

logging:
  level:
    root: INFO
    com:
      webank:
        cmdb: DEBUG
