server:
  port: 8081
  address: localhost
  servlet:
    context-path: /artifacts

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wecube_core?characterEncoding=utf8&serverTimezone=UTC
    username: db_user
    password: db_password

plugins:
  pacakge-name: artifacts
  wecmdb-server-url: http://localhost:8080/wecmdb

  saltstack-server-url: http://localhost:8082

  artifacts-s3-server-url: http://localhost:9000
  artifacts-s3-access-key: access_key
  artifacts-s3-secret-key: secret_key
