server:
  port: 8081
  address: localhost
  servlet:
    context-path: /artifacts

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

plugins:
  pacakge-name: artifacts

  wecube-gateway-server-url: http://localhost:19110

  artifacts-s3-server-url: http://localhost:9000
  artifacts-s3-access-key: access_key
  artifacts-s3-secret-key: secret_key
  artifacts-s3-bucket-name: wecube-artifacts