server:
  port: 18081
  address: localhost
  servlet:
    context-path: /artifacts

spring:
  profiles:
    active: dev
  messages:
    basename: message/artifacts_core_err_message
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

plugins:
  pacakge-name: artifacts

  wecube-gateway-server-url: http://localhost:19090
  artifacts-nexus-server-url: http://localhost:18888
  artifacts-nexus-username: admin
  artifacts-nexus-password: admin123
  artifacts-nexus-Repository: maven-releases
  cmdb-artifact-path: artifact_path

  artifacts-s3-server-url: http://localhost:9000
  artifacts-s3-access-key: access_key
  artifacts-s3-secret-key: secret_key
  artifacts-s3-bucket-name: wecube-artifacts
  jwt-signing-key:
  